version: 0.2

env:
  parameter-store:
    build_ssh_key: "build-ssh-key-secure"

phases:
  install:	
    runtime-versions:	
      nodejs: 10
  build:
    commands:
      - mkdir -p ~/.ssh
      - echo "$build_ssh_key" > ~/.ssh/id_rsa
      - chmod 600 ~/.ssh/id_rsa
      - rm -rf build/
      - echo Beginning Build
      - npm install
      - ls -la
      - ls -d "$PWD/"*
      - npm run build
      - ls -la
      - echo Build Complete
artifacts:
  files:
    - '**/*' 